# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
{START}+[RUN]="true"
{COMMITS}+[APPROVALS]="true"
SET.UP{commits}+[booleaan]="true
$ 100000USD,{currency}[Send  to:"0xb9f8609e934843583a811b1fb6102af36269f33"
